### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by ChromoX** [isra17/autobahn-autoreconnect#12]
```
11/6/2016 1:46:36 AM  Connection lost
11/6/2016 1:46:36 AM  Reconnecting
11/6/2016 1:46:36 AM  exception calling callback for <Future at 0x7f841d7e8cf8 state=finished returned list>
11/6/2016 1:46:36 AM  Traceback (most recent call last):
11/6/2016 1:46:36 AM  File "/usr/local/lib/python3.5/concurrent/futures/_base.py", line 297, in _invoke_callbacks
11/6/2016 1:46:36 AM    callback(self)
11/6/2016 1:46:36 AM  File "/usr/local/lib/python3.5/asyncio/futures.py", line 442, in _call_set_state
11/6/2016 1:46:36 AM    dest_loop.call_soon_threadsafe(_set_state, destination, source)
11/6/2016 1:46:36 AM  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 532, in call_soon_threadsafe
11/6/2016 1:46:36 AM    handle = self._call_soon(callback, args)
11/6/2016 1:46:36 AM  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 506, in _call_soon
11/6/2016 1:46:36 AM    self._check_closed()
11/6/2016 1:46:36 AM  File "/usr/local/lib/python3.5/asyncio/base_events.py", line 334, in _check_closed
11/6/2016 1:46:36 AM    raise RuntimeError('Event loop is closed')
11/6/2016 1:46:36 AM  RuntimeError: Event loop is closed
```

Not entirely sure what's happening.

**Comment by leameow** [comment]
Are you able to reliably reproduce or this happens sometime?
Also, using which release?
Thanks!

**Comment by ChromoX** [comment]
This happens sometimes. But it happens pretty regularly with a script I have. 

I'm using autobahn 0.16.1, and autobahn-autoconnect 0.1.0.

Later tonight I'll put together a small script that has the same problem. Would that be of help to you?
