### ISSUE TITLE
Asyncio add_signal_handler function not implemented in windows

### ISSUE THREAD

**Issue by AitchKay** [isra17/autobahn-autoreconnect#13]
In windows I get 

> Traceback (most recent call last):
>   File "autobahn_wamp_reconnecting_client_3.py", line 74, in <module>
>   File "autobahn_wamp_reconnecting_client_3.py", line 71, in doRun
>   File "site-packages\autobahn_autoreconnect\__init__.py", line 174, in run
>   File "asyncio\events.py", line 475, in add_signal_handler
> NotImplementedError
> Failed to execute script autobahn_wamp_reconnecting_client_3

line 174
```python
self._loop.add_signal_handler(signal.SIGTERM, self.stop)
```
The fix could be 
```python
try:
    loop.add_signal_handler(signal.SIGTERM, loop.stop)
except NotImplementedError:
    pass  # Ignore if not implemented. Means this program is running in windows.
```
as dealt with by the folks in autobahn in crossbario/autobahn-python#471

**Comment by leameow** [comment]
If you open a PR with the fix I will gladly merge it in.

**Comment by erwinkramer** [comment]
related: https://github.com/python/cpython/issues/137863
